
	// DEFINIÇÕES

#define TOTAL_REGISTROS 200
#define TOTAL_USUARIOS 100
#define TAMANHO_USUARIO 10
#define TAMANHO_SENHA 10
#define TAMANHO_NOME 20
#define TAMANHO_SOBRENOME 20
#define TAMANHO_DESCRICAO 200
#define TAMANHO_CODIGO_LIDO 10
#define TAMANHO_COPIA 30
#define ENTER 13